name: Test React
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Test application
        run: npm run test
