name: Test React App
on: push
jobs:
  test:
    runs-on: macos-12
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run tests
